name: elegionhack
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.0-dev.7
  flutter_secure_storage: ^4.2.1
  http: ^0.13.3
  url_launcher: ^6.0.12
  edge_alert: 
    git:
      url: https://github.com/ElvenVillage/EdgeAlert.git
      ref: master
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  
  assets:
    - images/